# Default values for dongtai.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# dongtai config
# appNamespace: dongtai-iast
skipistio: true
skipMysql: false
skipRedis: false
accessType: ClusterIP
images: registry.cn-beijing.aliyuncs.com/huoxian_pub    # or   dongtai
tag: latest

mysql:
  host: dongtai-mysql
  port: 3306
  name: dongtai_webapi
  user: root
  password: dongtai-iast

redis:
  host: dongtai-redis
  port: 6379
  password: 123456
  db: 0

sca:
  sca_token: 

storage:
  storageClassName: null
  # or You can choose to specify the storage class above, or create a custom multi-node read-write pvc below ！！！
  persistentVolumeClaim: iast-agent-pvc

csrfTrustOrigins: .example.com
secretKey: vbjlvbxfvazjfprywuxgyclmvhtmselddsefxxlcixovmqfpgy

smtp:
  server: smtp_server
  user: smtp_user
  password: smtp_password
  from_addr: from_addr
  ssl: False
  cc_addr: cc_addr