{{- if not .Values.skipMysql -}}
---
apiVersion: v1
kind: Service
metadata:
  name: dongtai-mysql
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ template "dongtai.fullname" . }}-mysql
spec:
  selector:
    app: {{ template "dongtai.fullname" . }}-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
{{- end -}}
{{- if not .Values.skipRedis -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "dongtai.fullname" . }}-redis
  name: dongtai-redis
  namespace: {{.Release.Namespace}}
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: {{ template "dongtai.fullname" . }}-redis
---
{{- end -}}
---
apiVersion: v1
kind: Service
metadata:
  name: dongtai-server-svc
  namespace: {{.Release.Namespace}}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ template "dongtai.fullname" . }}-server
  type: ClusterIP
---
{{- if or (eq .Values.accessType "NodePort") (eq .Values.accessType "LoadBalancer") (eq .Values.accessType "ClusterIP")  -}}
# Expose dongtai-web svc with {{ .Values.accessType }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "dongtai.fullname" . }}-web
  name: dongtai-web-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ template "dongtai.fullname" . }}-web
  type: {{ .Values.accessType }}
---
{{- end -}}
---
#dongtai-logstash服务
apiVersion: v1
kind: Service
metadata:
  name: dongtai-logstash-svc
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  ports:
    - name: agent-http
      port: 8082
      targetPort: 8082
      protocol: TCP
    - name: log-http
      port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: {{ template "dongtai.fullname" . }}-logstash
---
