---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-web
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: web
  labels:
    app: {{ template "dongtai.fullname" . }}-web
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-web
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      annotations:
        build_number: "{{ template "dongtai.fullname" . }}"
        {{- if not .Values.skipistio }}{{ include "dongtai.istiolabels" . | nindent 8 }}{{ end }}
      labels:
        app: {{ template "dongtai.fullname" . }}-web
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-web-container
          image: {{ .Values.images }}/dongtai-web:{{ .Values.tag }}
          imagePullPolicy: Always
          {{- include "deploy.resources" . | nindent 10 }}
          volumeMounts:
            - name: configfile
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: configfile
          configMap:
            name: dongtai-web-nginx-conf
---
# dongtai-server服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-server
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: server
  labels:
    app: {{ template "dongtai.fullname" . }}-server
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-server
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      annotations:
        build_number: "{{ template "dongtai.fullname" . }}"
        {{- if not .Values.skipistio }}{{ include "dongtai.istiolabels" . | nindent 8 }}{{ end }}
      labels:
        app: {{ template "dongtai.fullname" . }}-server
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-server-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          env:
            - name: DONGTAI_CONCURRENCY
              value: --processes 4
            {{- range $key, $value :=  .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- include "deploy.config" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}
      {{- if .Values.somaxconn }}
      {{- include "deploy.initContainers" . | nindent 6 }}
      {{- end }}
---

#dongtai-worker-task服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-worker-task
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: {{ template "dongtai.fullname" . }}-worker-task
  labels:
    app: {{ template "dongtai.fullname" . }}-worker-task
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-worker-task
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ template "dongtai.fullname" . }}-worker-task
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-worker-task-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          command: [ "/bin/bash","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "beat" ]
          {{- include "deploy.config" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}
---
# dongtai-worker-high-freq服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-worker-high-freq
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: {{ template "dongtai.fullname" . }}-worker-high-freq
  labels:
    app: {{ template "dongtai.fullname" . }}-worker-high-freq
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-worker-high-freq
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ template "dongtai.fullname" . }}-worker-high-freq
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-worker-high-freq-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-high-freq" ]
          env:
            - name: DONGTAI_CONCURRENCY
              value: -P gevent --concurrency=121
          {{- include "deploy.config" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}
---
# dongtai-worker-beat服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-worker-beat
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: {{ template "dongtai.fullname" . }}-worker-beat
  labels:
    app: {{ template "dongtai.fullname" . }}-worker-beat
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-worker-beat
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ template "dongtai.fullname" . }}-worker-beat
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-worker-beat-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-beat" ]
          env:
            - name: DONGTAI_CONCURRENCY
              value: --concurrency=2
          {{- include "deploy.config" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}

---
# dongtai-worker-sca服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-worker-sca
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: {{ template "dongtai.fullname" . }}-worker-sca
  labels:
    app: {{ template "dongtai.fullname" . }}-worker-sca
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-worker-sca
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ template "dongtai.fullname" . }}-worker-sca
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-worker-sca-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-sca" ]
          env:
            - name: DONGTAI_CONCURRENCY
              value: -P gevent --concurrency=10
          {{- include "deploy.config" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}
---
{{- if .Values.max }}
# dongtai-worker-report-only服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-worker-report-only
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: {{ template "dongtai.fullname" . }}-worker-report-only
  labels:
    app: {{ template "dongtai.fullname" . }}-worker-report-only
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-worker-report-only
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ template "dongtai.fullname" . }}-worker-report-only
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-worker-report-only-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-report-only" ]
          {{- include "deploy.configmax" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}
---
# dongtai-worker-chain服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-worker-chain
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: {{ template "dongtai.fullname" . }}-worker-chain
  labels:
    app: {{ template "dongtai.fullname" . }}-worker-chain
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-worker-chain
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ template "dongtai.fullname" . }}-worker-chain
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-worker-chain-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-chain" ]
          env:
            - name: DONGTAI_CONCURRENCY
              value: --concurrency=12
          {{- include "deploy.config" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}
---
{{- end }}

# dongtai-worker-other服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-worker-other
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: {{ template "dongtai.fullname" . }}-worker-other
  labels:
    app: {{ template "dongtai.fullname" . }}-worker-other
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-worker-other
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ template "dongtai.fullname" . }}-worker-other
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-worker-other-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-other" ]
          env:
            - name: DONGTAI_CONCURRENCY
              value: --concurrency=10
          {{- include "deploy.config" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}


---
# dongtai-worker-es服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-worker-es
  namespace: {{.Release.Namespace}}
  annotations:
    kubesphere.io/description: {{ template "dongtai.fullname" . }}-worker-es
  labels:
    app: {{ template "dongtai.fullname" . }}-worker-es
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "dongtai.fullname" . }}-worker-es
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ template "dongtai.fullname" . }}-worker-es
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: {{ template "dongtai.fullname" . }}-worker-es-container
          image: {{ .Values.images }}/dongtai-server:{{ .Values.tag }}
          command: [ "/bin/sh","/opt/dongtai/deploy/docker/entrypoint.sh" ]
          args: [ "worker-es" ]
          env:
            - name: DONGTAI_CONCURRENCY
              value: -P gevent --concurrency=64
          {{- include "deploy.config" . | nindent 10 }}
      {{- include "deploy.config.vo" . | nindent 6 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dongtai.fullname" . }}-logstash
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ template "dongtai.fullname" . }}-logstash
    {{- include "dongtai.labels" .  | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels: 
      app: {{ template "dongtai.fullname" . }}-logstash
      {{- include "dongtai.labels" .  | nindent 6 }}
  template:
    metadata:
      annotations:
        build_number: "{{ template "dongtai.fullname" . }}"
        {{- if not .Values.skipistio }}{{ include "dongtai.istiolabels" . | nindent 8}}{{ end }}
      labels:
        app: {{ template "dongtai.fullname" . }}-logstash
        {{- include "dongtai.labels" .  | nindent 8 }}
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - image: {{ .Values.images }}/dongtai-logrotate:{{ .Values.tag }}
        name: logrotate
        securityContext:
          runAsUser: 0
        {{ include "deploy.imagePullPolicy" . }}
        {{- if .Values.storage.persistentVolumeClaim }}
        volumeMounts:
        - name: {{ template "dongtai.fullname" . }}-log-path
          mountPath: /tmp/logstash
        {{- end }}
      - image: {{ .Values.images }}/dongtai-logstash:{{ .Values.tag }}
        name: logstash
        securityContext:
          runAsUser: 0
        {{ include "deploy.imagePullPolicy" . }}
        env:
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              key: database
              name: logstash-cm
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              key: username
              name: logstash-cm
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              key: password
              name: logstash-cm
        ports:
        - containerPort: 8082
          protocol: TCP
          name: agent-http
        - containerPort: 8083
          protocol: TCP
          name: log-http
        resources:
          requests:
            cpu: 1000m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 4000Mi
#         livenessProbe:
#           failureThreshold: 1
#           periodSeconds: 5
#           successThreshold: 1
#           tcpSocket:
#             port: 9600
#           timeoutSeconds: 1
#         readinessProbe:
#           failureThreshold: 3
#           initialDelaySeconds: 30
#           periodSeconds: 5
#           successThreshold: 1
#           tcpSocket:
#             port: 9600
#           timeoutSeconds: 1
#         startupProbe:
#           failureThreshold: 40
#           periodSeconds: 5
#           successThreshold: 1
#           tcpSocket:
#             port: 9600
#           timeoutSeconds: 1
{{- if .Values.storage.persistentVolumeClaim }}
        volumeMounts:
        - name: {{ template "dongtai.fullname" . }}-log-path
          mountPath: /tmp/logstash
      volumes:
      - name: {{ template "dongtai.fullname" . }}-log-path
        persistentVolumeClaim:
          {{ include "deploy.config.persistentVolumeClaim" . }}
{{ end -}}
      {{- if .Values.somaxconn }}
      {{- include "deploy.initContainers" . | nindent 6 }}
      {{- end }}
---
