name: Deploy DongTai Server To Dev

on:
  push:
    branches: [ "main"  ]
  workflow_dispatch:

jobs:
  Deploy-to-dev:
    if: ${{ github.event_name == 'workflow_dispatch' || github.repository_owner == 'HXSecurity' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_HONGKONG }}
          username: ${{ secrets.ALIYUN_DOCKERHUB_USER }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PASSWORD }}

      - name: Generate version file
        run: |
          #bash .github/workflows/config_update.sh
          #bash .github/workflows/config_update.sh "${{ steps.release.outputs.VERSION }}"

      - name: Setup Ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.CHART_OSS_ENDPOINT }}
          access-key-id: ${{ secrets.CHART_OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.CHART_OSS_ACCESS_KEY_SECRET }}
          
      - name: Download Agent
        run: |
          ossutil cp oss://dongtai-helm-charts/agent_test/java/latest/ ./ --include "*.jar" -r
          ossutil cp oss://dongtai-helm-charts/agent_test/python/ ./  --include "*.tar.gz" -r
          
      - name: Generate version file
        run: |
          echo "REPLACE INTO project_version_control (version, component_name, component_version_hash) VALUES('${{ github.run_number }}.0.0', '${{ github.event.repository.name }}', '${GITHUB_SHA}');" >> ./deploy/docker/version.sql

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64
          tags: | 
            registry.cn-hongkong.aliyuncs.com/secnium/dongtai-server-test:latest
            registry.cn-hongkong.aliyuncs.com/secnium/dongtai-server-test:1.0.${{github.run_number}}

      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_TEST_DATA }}
        with:
          args: |
            find .github/deploy/deploy-dongtai-server-test.yml -type f -exec sed -i 's/VERSION/1.0.${{github.run_number}}/g' {} \;
            ls .github/deploy/deploy-dongtai-server-test.yml | xargs -I {} kubectl apply -f {}
