
name: "MypyCheck"

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  # This workflow contains a single job called "build"
  Run-MypyCheck:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Django Unit Testing
        run: |
          mypy --show-error-codes --ignore-missing-imports --disable-error-code var-annotated  --disable-error-code union-attr --disable-error-code  dict-item  --disable-error-code  list-item  --disable-error-code attr-defined  --disable-error-code index --disable-error-code arg-type --disable-error-code assignment --disable-error-code misc .
