
name: "Pep8Check"

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  # This workflow contains a single job called "build"
  Run-Pep8Check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Django Unit Testing
        run: |
          pep8  --ignore=E501,E402,E231,E302,E301,E303,E251,E265,W291,E126,W293,W391,W503,E128,E127,E122,E241,E225,E401,E101,E125,E131,E266,E701,W191 --statistics .
